ARG version
FROM almalinux:${version:-8}
#RUN cat /etc/*releasez
ARG COURSE=Docker 
ARG TRAINER=sivakumar 
ARG Duration=120HRS
ENV Duration=${Duration}
RUN echo "Course is: ${COURSE}, Duration is: ${TRAINER}, Duration is: ${Duration}" 
CMD ["sleep", "100"]

